repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    language: python
    files: ^eap_backend/
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.6.0
  hooks:
  - id: prettier
    files: ^frontend/src/
    args: [--write]
