version: "3"
services:
  eap_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - eap_backend
    ports:
      - "3000:3000"
    networks:
      - eap_nw

  eap_backend:
    build:
      context: ./eap_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - eap_nw

networks:
  eap_nw:
    driver: bridge
