name: backend-docker

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: actions/checkout@v3
      - working-directory: eap_backend
        run: docker build -t turingassuranceplatform/eap_backend:test -f Dockerfile .
      - run: docker push turingassuranceplatform/eap_backend:test
