name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.12
          architecture: x64
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8 --max-line-length 88
        working-directory: eap_backend
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8'
          github-token: ${{ secrets.GITHUB_TOKEN }}
